YOLOV5_PT: /home/class-undefined/code/AcademicGarbage/sdk/epoch-1.pt # 模型
YOLOV5_DETECT: /home/class-undefined/code/AcademicGarbage/sdk/yolov5/detect.py # 预测脚本
YOLOV5_DETECT_ARGS: --save-conf --save-txt --iou-thres=0.25 --conf-thres=0.45 # 预测附加参数
http_proxy: http://127.0.0.1:7890
